### ISSUE TITLE
[Rockbot 2] Bugs found by me

### ISSUE THREAD

**Issue by fervi** [protoman/rockbot#112]
Welcome, I will describe the bugs I found in the game (although they are not accurate and I will record them if I pass the second time).

In the gladiator board there is a possibility to go down and up. If you go down, you will get stuck in the wall. If you go up, you can go up the level as long as you do not go up at the beginning of the board (the transition is not very visible). When you go through them, you will get stuck in the wall.

The levels with the bosses (especially with the blocks) are broken. With the blocks there is no texture and you can hit the mine (the best way to fly over the hole).

And what is Betabot about? It has not been said anywhere.

**Comment by protoman** [comment]
I am closing this issue until further information is provided (what is gladiator board?).
