### ISSUE TITLE
Potential fixes for compiling for PS2

### ISSUE THREAD

**Issue by GeoVa19** [protoman/rockbot#113]
I tried to build rockbot for PlayStation 2, but I encountered some errors. I tried to fixed them. My fixes are the following:

- in Rockbot.pro, instead of
`SJPCM.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/SJPCM.irx ../ports/ps2/SJPCM.s SJPCM`,
`cdvd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/cdvd.irx ../ports/ps2/cdvd.s cdvd`,
`usbd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/usbd.irx ../ports/ps2/usbd.s usbd`,
`usbhdfsd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/usbhdfsd.irx ../ports/ps2/usbhdfsd.s usbhdfsd` and
 `LIBS = $(SUBLIBS) -mno-crt0 -T/usr/local/ps2dev/ps2sdk/ee/startup/linkfile /usr/local/ps2dev/ps2sdk/ee/startup/crt0.o ../ports/ps2/cdvd.s ../ports/ps2/usbd.s ../ports/ps2/usbhdfsd.s ../ports/ps2/SJPCM.s -L. -lstdc++ -lc -lstlport -L$(PS2DEV)/gsKit/lib -L../lib -L$(PS2SDK)/ports/lib -lSDL_gfx -lSDL_image -ljpeg -ltiff -lpng -lz -ldebug -lSDL_ttf -lsdlmixer -lfreetype -lm -lcdvd -lsdl -lmf -lpacket -ldma -lfileXio -L/usr/local/ps2dev/ps2sdk/ee/lib -L/usr/local/ps2dev/gsKit/lib -L/usr/local/ps2dev/ps2sdk/ports/lib -lmc`, 
it should probably be
`SJPCM.commands = $(PS2SDK)/bin/bin2s ports/ps2/SJPCM.irx ports/ps2/SJPCM.s SJPCM`
`cdvd.commands = $(PS2SDK)/bin/bin2s ports/ps2/cdvd.irx ports/ps2/cdvd.s cdvd`,
`usbd.commands = $(PS2SDK)/bin/bin2s ports/ps2/usbd.irx ports/ps2/usbd.s usbd`,
`usbhdfsd.commands = $(PS2SDK)/bin/bin2s ports/ps2/usbhdfsd.irx ports/ps2/usbhdfsd.s usbhdfsd`
 and `LIBS = $(SUBLIBS) -mno-crt0 -T/usr/local/ps2dev/ps2sdk/ee/startup/linkfile /usr/local/ps2dev/ps2sdk/ee/startup/crt0.o ports/ps2/cdvd.s ports/ps2/usbd.s ports/ps2/usbhdfsd.s ports/ps2/SJPCM.s -L. -lstdc++ -lc -lstlport -L$(PS2DEV)/gsKit/lib -L../lib -L$(PS2SDK)/ports/lib -lSDL_gfx -lSDL_image -ljpeg -ltiff -lpng -lz -ldebug -lSDL_ttf -lsdlmixer -lfreetype -lm -lcdvd -lsdl -lmf -lpacket -ldma -lfileXio -L/usr/local/ps2dev/ps2sdk/ee/lib -L/usr/local/ps2dev/gsKit/lib -L/usr/local/ps2dev/ps2sdk/ports/lib -lmc`  since ports/ is in the same directory with Rockbot.pro file.

- in ports/ps2/modules.h, the implementation of `cdInit` function is missing, so I commented this line (line 73).

- in projectilelib.cpp, the line `angle = atan2(abs(dist_y), abs(dist_x));` (line 396), should be `angle = (float) atan2(abs(dist_y), (float) abs(dist_x));`, since there was an ambiguity in function overloading.

- in graphic/draw.cpp, there is the following problem. The method `at`  of `std::map` (called in `input_images_map` variable) was introduced in C++11 (https://en.cppreference.com/w/cpp/container/map/at). Ee-g++ compiler is obviously older, so this method does not exist (except in case there is a way to update ee-g++ but I personally doubt it). I fixed it by adding something like this: 
`#if defined(PLAYSTATION2) 
graphLib.surfaceFromFile(filename, &input_images_map[INPUT_IMAGES_DPAD_LEFTRIGHT]);
 #else
graphLib.surfaceFromFile(filename, &input_images_map.at(INPUT_IMAGES_DPAD_LEFTRIGHT));#endif` 
I have not tested any other platform besides Linux and PS2, so I don't know if the Wii build, for example, needs the same instruction as in the case of PS2.

- lastly, the compiler gave me an error that, in file/v4/file_save_v4.h file, the type `int8_t` was not recognized. This may be due to lack of include files that contain the appropriate typedef for this type or I did something wrong. Anyway, in case the compiler shows a similar error message, I'd suggest adding `typedef signed char int8_t;` before `typedef int8_t Sint8;`. This worked for me.

By following these steps, I was able to build the game for the PS2. I don't know if without these changes the compiler would still be able to build the game. At least in my case, it didn't.

**Comment by protoman** [comment]
Hey, I am very happy to see someone trying to compile the project on PS2.
My original PS2 died a while ago, so that is why there are such errors, as
I stopped caring for it. In the end, I bough some new and repleaced the
motherboard of the original I owned, so I had three; gave on as a gift and
have two, eheheh.
I will try to fix those issues, and thanks for contacting me about it, when
I have a bit of time. I am currently working on a new game that needs some
initial push.
--
Iuri Fiedoruk, Software Developer

**Comment by GeoVa19** [comment]
I have to say that I discovered this repository a few days ago and I really like it! I have some other issues to address.

I would like to ask you, although I have successfuly run the 1.1.1 version I found at https://rockbot.upperland.net/?page_id=301 for the PS2, I cannot run the new build even though I have compiled it (and after applying some other changes, which I will describe in other issues). Does the rockbot.elf run on its own without the build/ directory, or should I include both the .elf and the build/ in the same directory, e.g. rockbot/? But even though I've tried, it still doesn't work (I run it via a USB stick).

**Comment by protoman** [comment]
Witch repository are you using? I am currently on
https://github.com/protoman/rockbot
You need to copy the data files into the USB device you are using. There is
a .sh file, under packages, that will create the correct folder structure
for the PS2 build.
--
Iuri Fiedoruk, Software Developer

**Comment by GeoVa19** [comment]
I use the same repository. 

I ran the .sh, but no luck. I guess there's a problem with the value of `FILEPATH` variable in ./main.cpp. As I described in #114, I had to change the value of the variable in order to boot the Linux version. So I think that I have to do something similar for the PS2 version, i.e. editing line 272 (https://github.com/protoman/rockbot/blob/master/main.cpp#L272) to something like: `FILEPATH = "mass:/PS2/Rockbot/build/";`, since all the assets are under the ./build/ directory. But I am not 100% sure.

**Comment by protoman** [comment]
OK, I will try to build and run the project from my USB device, now that I
again have a PS2 device, and check it.
But be aware that due to the loss on my old PS2, I did not had the time to
fix the build for Playstation, so let's see how it goes.
Do you by any change have a debug method to run ps2 programs? I use a cd
disc to boot a debugger, so I can run the apps from my linux. Before I had
to cross a network cable for all my home, but recently I've changed the net
and phone provider and I can now use an small cable as the router in on the
table the PS2 is on :)
That will easy development, a lot, eheheh.

--
Iuri Fiedoruk, Software Developer

**Comment by GeoVa19** [comment]
No, I am new to PS2 homebrew development. A few hours ago I managed to compile ps2link and run it on the PS2. But I didn't manage to run any .elfs remotely, so, go figure, hahaha! 

But I just found https://github.com/mlafeldt/ps2rd, so I will give it a try!

**Comment by protoman** [comment]
I pushed the code with the fixes, including yours - thanks a lot, it made
me take much less time for that.
I also create a mkspec for qt creator and placed into ports/ps2/qmake.spec.
This is useful if, like on my system, qmake adds g++11 into the gcc configs.

I will now add a network cacle into my PS2 and burn a new cd image with the
correct IP address for it. Also because I have no clue where I left my CDs
with the ps2client. It's been a while since I made that kind of stuff, so
it may take a while...
--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
OK, with the PS2LINK set here, I can see the console output when running
the game.
It is freezing here:
mkdir name mc0:Rockbot/

The code for that part is:

    #ifdef PLAYSTATION2

        PS2_load_MC();

        SAVEPATH = "mc0:Rockbot/";


        if (fioMkdir(SAVEPATH.c_str()) < 0) {

            std::cout << "main - warning: could not create '" <<
SAVEPATH << "' folder" << std::endl; std::fflush(stdout);

            /// @TODO - check if directory exists

        } else {

            std::cout << "Folder '" << SAVEPATH << "' created" <<
std::endl; std::fflush(stdout);

        }


    #endif


--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
I've made a few more fixes, tring to improve performance, because older
versions run at 30 fps in 8 bit color mode, while this one at 60 in 16/24
bit, that PS2 have difficulty to mantain.
There is some screen updating problem that shows interference that I still
was not able to check. Also, I've hardcoded path do mass:/PS2/Rockbot. So
you need to run the PS2.sh script in build/packages and drop the folder
into mass:/PS2 path.

[image: image.png]

[image: image.png]

--
Iuri Fiedoruk, Software Developer

**Comment by GeoVa19** [comment]
I compiled the program after making some minor changes (the first two bullets I mentioned in this issue) and it... kind of boots. It shows me a window with a problematic path. It looked something like this: `mass:PS2/rockbot/build//games/Rockbot2...` I fixed this by adding `FILEPATH = StringUtils::clean_filename(FILEPATH)` after line 488 in main.cpp (https://github.com/protoman/rockbot/blob/master/main.cpp#L488). 

I compiled the program. But it again showed me a similar path, now without the double slash. It doesn't even boot till the Game Menu, as in the Linux version. I wasn't able to see the full path but I bet it's this one: `mass:PS2/rockbot/build/games/Rockbot2/images/tilesets/anim/lab_lava.png` This file is missing and I guess that's why it doesn't boot. (#114)

Is the program working, in your case? Because if it does, then I'm doing something wrong. I've run the PS2.sh script and the file structure in mass looks like this (`ls` in `mass:/PS2/Rockbot`).
Output: `fonts/ games/ rockbot.elf shared/ strings_ingame.dat`

Did you upload two .png files in your last post? I am not able to see them. It just says: `[image: image.png]`

**Comment by protoman** [comment]
Yes, it boots to me.
There is an Error #1 that appear on boot, those are just warnings for icon
files used to create the save file on PS2. If you wait a while, it will
proceed.
I set a quickload flag to load the game directly so it will not show any
menus.

If you are interested and can plug your PS2 in your home network, I can
gice you the ways to run the elf from a console session, so you can see the
loading and devug/output messages.

Em qui, 21 de fev de 2019 09:53, George Vasios <notifications@github.com>
escreveu:

**Comment by requeijaum** [comment]
I'm interested in building the last version.

I think that it's possible to use PCSX2 (v1.5.0-dev-2779 from Orphis [last ver. to support D3D9]) with https://github.com/TheLastRar/CLR-DEV9 and https://github.com/TheLastRar/CLR-USB for testing.

I got some games working with HDD and Ethernet online gameplay - including a match of *Need For Speed Underground 1* against my real PS2.

Since I'm working for NewsInside.org community... I may be fiddling with RockBot PS2 builds once in a while. I just need to get my environment running and get used to the PS2SDK.

**Comment by requeijaum** [comment]
- Just installed qtcreator and got a working Makefile.
- Compiled ISJPCM and renamed it's IRX to put on the ports/ps2/ folder.
- Corrected the PATH in line 491 of the Makefile - where it writes ../ports/ps2/, but must be ./ports/ps2/ - on our actual directory tree.
- Just got @ps2dev/ps2sdk-ports and @ps2dev/gsKit installed. Compiled SDL too.
- Now I only got compilation errors for CDVD related stuff.

![Captura de Tela 2019-04-24 às 11 19 01](https://user-images.githubusercontent.com/5564635/56666974-4bcd3780-6683-11e9-9a95-8054ffb5956e.png)

Keep in mind that the there is a **libcdvd.a** with it's compiler files. The scene changed a lot in PS2SDK due to OpenPS2Loader technical advances. You may not embed the CDVDMAN/FSV IRX on the ELF, because now it's a full-fledged library.

A quick fix might be including <libcdvd.h> and <libcdvd-rpc.h> and get it's interfaces working. But I don't know how to do it... yet.

**Comment by protoman** [comment]
Feel free to remove the cd part. I never use it anyway. nowadays I think no
one will burn a CD with the game, as loading from USB is very spread
already :)
--
Iuri Fiedoruk, Software Developer

**Comment by requeijaum** [comment]
I ommited the loading and initialization of the CDVD modules... got a new problem.

![Captura de Tela 2019-04-24 às 11 29 05](https://user-images.githubusercontent.com/5564635/56667508-576d2e00-6684-11e9-8874-6a58af0bee24.png)

I will tell the NewsInside team about this. They might help me fixing this.


-----

EDIT: fixed the PATH again to ./ports/ps2 on the build recipe...

Here is a new error:

![Captura de Tela 2019-04-24 às 11 34 02](https://user-images.githubusercontent.com/5564635/56667823-e4b08280-6684-11e9-9db5-8d9515fd003a.png)

**Comment by protoman** [comment]
Cara, vc é brasileiro ou português?
Porque diabos estamos alando em inglês? Ahahahahah. Vi agora teu prompt de
comando em PT :D
--
Iuri Fiedoruk, Software Developer

**Comment by requeijaum** [comment]
Prefiro falar inglês, haha! Pra quem for ler o issue.

**Comment by protoman** [comment]
Este problema é porque, no meu qmake, tem umas macros para gerar estes
arquivos .s.
Da última vez que eu tentei, estava tudo compilando bem, tem como você me
passar as mudanças que fez para eu testar aqui?
De repente é algo faltando no teu SDK, se quiser posso disponibilizar o meu
pelo google drive, ou algo assim.
--
Iuri Fiedoruk, Software Developer

**Comment by requeijaum** [comment]
O culpado é a ps2sdk-ports/stlport ... não consegui compilar.

```console
rafaelfrequiao@norsul:/usr/local/ps2dev/ps2sdk-ports/stlport$ make
mkdir -p lib/obj/GCC/
make -C src all
make[1]: Entering directory '/usr/local/ps2dev/ps2sdk-ports/stlport/src'
mkdir: não foi possível criar o diretório “../lib”: Arquivo existe
common_rules.mak:29: recipe for target 'platform' failed
make[1]: [platform] Error 1 (ignored)
mkdir: não foi possível criar o diretório “../lib/obj”: Arquivo existe
common_rules.mak:29: recipe for target 'platform' failed
make[1]: [platform] Error 1 (ignored)
mkdir: não foi possível criar o diretório “../lib/obj/GCC”: Arquivo existe
common_rules.mak:29: recipe for target 'platform' failed
make[1]: [platform] Error 1 (ignored)
mkdir ../lib/obj/GCC/Release
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 dll_main.cpp -c -o ../lib/obj/GCC/Release/dll_main.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 fstream.cpp -c -o ../lib/obj/GCC/Release/fstream.o
fstream.cpp: In function `bool _SgI::__is_regular_file(int)':
fstream.cpp:209: warning: ignoring #pragma unused 
fstream.cpp: In function `streamoff _SgI::__file_size(int)':
fstream.cpp:240: warning: ignoring #pragma unused 
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 strstream.cpp -c -o ../lib/obj/GCC/Release/strstream.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 sstream.cpp -c -o ../lib/obj/GCC/Release/sstream.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 ios.cpp -c -o ../lib/obj/GCC/Release/ios.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 streambuf.cpp -c -o ../lib/obj/GCC/Release/streambuf.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 stdio_streambuf.cpp -c -o ../lib/obj/GCC/Release/stdio_streambuf.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 istream.cpp -c -o ../lib/obj/GCC/Release/istream.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 ostream.cpp -c -o ../lib/obj/GCC/Release/ostream.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 iostream.cpp -c -o ../lib/obj/GCC/Release/iostream.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 codecvt.cpp -c -o ../lib/obj/GCC/Release/codecvt.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 collate.cpp -c -o ../lib/obj/GCC/Release/collate.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 ctype.cpp -c -o ../lib/obj/GCC/Release/ctype.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 monetary.cpp -c -o ../lib/obj/GCC/Release/monetary.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 num_get.cpp -c -o ../lib/obj/GCC/Release/num_get.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 num_put.cpp -c -o ../lib/obj/GCC/Release/num_put.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 num_get_float.cpp -c -o ../lib/obj/GCC/Release/num_get_float.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 num_put_float.cpp -c -o ../lib/obj/GCC/Release/num_put_float.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 numpunct.cpp -c -o ../lib/obj/GCC/Release/numpunct.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 time_facets.cpp -c -o ../lib/obj/GCC/Release/time_facets.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 messages.cpp -c -o ../lib/obj/GCC/Release/messages.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 locale_impl.cpp -c -o ../lib/obj/GCC/Release/locale_impl.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 locale.cpp -c -o ../lib/obj/GCC/Release/locale.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 locale_catalog.cpp -c -o ../lib/obj/GCC/Release/locale_catalog.o
ee-g++  -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 facets_byname.cpp -c -o ../lib/obj/GCC/Release/facets_byname.o
cc -I../stlport -Wall -W -Wno-sign-compare -Wno-unused -Wno-uninitialized -I/usr/local/ps2dev/ps2sdk/common/include -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ee/include/c++/3.2.2 -I/usr/local/ps2dev/ee/include/c++/3.2.2/ee -O2 c_locale.c -c -o ../lib/obj/GCC/Release/c_locale.o
In file included from /usr/local/ps2dev/ps2sdk/ee/include/malloc.h:21:0,
                 from /usr/local/ps2dev/ps2sdk/ee/include/../include/stdlib.h:21,
                 from ../stlport/stdlib.h:23,
                 from c_locale.c:21:
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:20:2: error: #error Either _EE or _IOP must be defined!
 #error Either _EE or _IOP must be defined!
  ^~~~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:86:23: error: unknown type name ‘u32’
 static inline u8  _lb(u32 addr) { return *(vu8 *)addr; }
                       ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:87:23: error: unknown type name ‘u32’
 static inline u16 _lh(u32 addr) { return *(vu16 *)addr; }
                       ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:88:15: error: unknown type name ‘u32’
 static inline u32 _lw(u32 addr) { return *(vu32 *)addr; }
               ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:88:23: error: unknown type name ‘u32’
 static inline u32 _lw(u32 addr) { return *(vu32 *)addr; }
                       ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:90:32: error: unknown type name ‘u32’
 static inline void _sb(u8 val, u32 addr) { *(vu8 *)addr = val; }
                                ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:91:33: error: unknown type name ‘u32’
 static inline void _sh(u16 val, u32 addr) { *(vu16 *)addr = val; }
                                 ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:92:24: error: unknown type name ‘u32’
 static inline void _sw(u32 val, u32 addr) { *(vu32 *)addr = val; }
                        ^~~
/usr/local/ps2dev/ps2sdk/common/include/tamtypes.h:92:33: error: unknown type name ‘u32’
 static inline void _sw(u32 val, u32 addr) { *(vu32 *)addr = val; }
                                 ^~~
In file included from /usr/local/ps2dev/ps2sdk/ee/include/../include/stdlib.h:21:0,
                 from ../stlport/stdlib.h:23,
                 from c_locale.c:21:
/usr/local/ps2dev/ps2sdk/ee/include/malloc.h:37:36: error: unknown type name ‘u32’
 void __mem_walk_read(void * token, u32 * size, void ** ptr, int * valid);
                                    ^~~
common_percent_rules.mak:7: recipe for target '../lib/obj/GCC/Release/c_locale.o' failed
make[1]: *** [../lib/obj/GCC/Release/c_locale.o] Error 1
make[1]: Leaving directory '/usr/local/ps2dev/ps2sdk-ports/stlport/src'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2
rafaelfrequiao@norsul:/usr/local/ps2dev/ps2sdk-ports/stlport$ 
```

**Comment by protoman** [comment]
Oki-doki, so we'll keep in english.
Please look at the .pro file, there is this pre-compilation requirements:

	# pre-build commands

	SJPCM.target = SJPCM.s

	SJPCM.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/SJPCM.irx
../ports/ps2/SJPCM.s SJPCM

	cdvd.target = cdvd.s

	cdvd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/cdvd.irx
../ports/ps2/cdvd.s cdvd

	usbd.target = usbd.s

	usbd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/usbd.irx
../ports/ps2/usbd.s usbd

	usbhdfsd.target = usbhdfsd.s

	usbhdfsd.commands = $(PS2SDK)/bin/bin2s ../ports/ps2/usbhdfsd.irx
../ports/ps2/usbhdfsd.s usbhdfsd


This kinda of transforms the IRX into a .s so it can be incorporated
into the project, if I remember it right.

Please let me know if some file is missing.

I can also pack the PS2 SDK into a zip file and make it available in
google drive, because I made a few fixes and changes into PS2's SDL
version.


--
Iuri Fiedoruk, Software Developer

**Comment by requeijaum** [comment]
I think that would be better to keep working with the upstream PS2SDK and it's libraries ports.
How to fix STLPort? The errors are produced by the EE-GCC compiler. :)

**Comment by protoman** [comment]
I don't recall this error.
Maybe your compiler is newer than mine - I am using Mint 19 right now, with
4.8 for PS2 dev.
Here are the steps I did to build the SDK and SDL for PS2, maybe it is
related to the kernel I commented out:

Colocar no .bashrc
export PS2DEV=/usr/local/ps2dev
export PS2SDK=$PS2DEV/ps2sdk export
export
PS2SDKSRC=/media/iuri/SamsungEXT4/development/SDK/PS2/ps2toolchain/build/ps2sdk/

#export PS2SDKSRC=/usr/local/ps2dev/ps2sdk

PATH=$PATH:$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin:$PS2DEV/dvp/bin:$PS2SDK/bin

Executar tudo como root (sudo su) para maior facilidade.

cd /arquivos/development/SDK/PS2/
git clone https://github.com/ps2dev/ps2toolchain.git
cd ps2toolchain
sudo CC=gcc-4.8 ./toolchain-sudo.sh


******** export PS2SDKSRC=/arquivos/development/SDK/BACKUP/PS2/ps2sdk
(apontar para ele mesmo)

cd ..
git clone https://github.com/ps2dev/ps2sdk
cd ps2sdk
export PS2SDKSRC=/media/iuri/SamsungEXT4/development/SDK/PS2/ps2sdk
make
export PS2DEV=/usr/local/ps2dev
export PS2SDK=$PS2DEV/ps2sdk
export PS2SDKSRC=/usr/local/ps2dev/ps2sdk
sudo -E make install

### abrir /usr/local/ps2dev/ps2sdk/ee/include/kernel.h e comentar enum
_sif_regs ###

cd ..
git clone https://github.com/ps2dev/gsKit
cd gsKit
make
sudo -E make install

cd ..
git clone https://github.com/ps2dev/ps2sdk-ports.git
cd ./ps2sdk-ports/

cd sdl
make clean
make
sudo -E make install

cd ../..
git clone https://github.com/ps2dev/ps2client
cd ps2client
make
sudo -E make install
cd ..


cd zlib
make clean
make
sudo -E make install
cd ..

cd libpng
make clean
make
sudo -E make install
cd ..

cd libjpeg
make clean
make
sudo -E make install
cd ..


********* copiada libtiff do SDK antigo ********
cd libtiff
make clean
make
cp libtiff.a $PS2SDK/ports/lib
cp tiff.h $PS2SDK/ports/include
cp tiffio.h $PS2SDK/ports/include
cp tiffvers.h $PS2SDK/ports/include
cd ..

********* copiada libjpg do SDK antigo ********
cd libjpg/libjpg
make clean
make
cp -Rv include/* $PS2SDK/ports/include
cp -Rv lib/* $PS2SDK/ports/lib
cd ../..

cd freetype-2.4.12
make clean
make setup ps2; make
mkdir -p $PS2SDK/ports/lib
cp objs/libfreetype.a $PS2SDK/ports/lib
mkdir -p $PS2SDK/ports/include
cp -Rv include/* $PS2SDK/ports/include
cd ..

cd sdlmixer
make clean
make
sudo -E make install
cd ..

cd sdlimage
make clean
make
sudo -E make install
cd ..

cd stlport
make clean
make
sudo -E make install
cd ..

cd sdlgfx
mkdir lib
make clean
make
cd ..

--
Iuri Fiedoruk, Software Developer

**Comment by requeijaum** [comment]
> ### abrir /usr/local/ps2dev/ps2sdk/ee/include/kernel.h e comentar enum _sif_regs ###

Why to do this?

And I only couldn't get stlport compiled - check my previous edited message.

**Comment by protoman** [comment]
Betas me. I wrote that several years ago.
Don't know even if still needed with latest versions. But, I do recall
there were some errors in PS2 C++ threads, that make the sound terrible in
SDL. So, maybe it is a build fix or a threads fix :)
--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
I will close it, as I am able to build and no further feedback was sent.
Please feel free to reopen the issue if wanted or needed.
