### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#118]
1
Sfx delay 
Demora para que o som apareça
2
Música.
Após morrer a música inicia de onde você morreu
Depois de tocar um trecho da versão antiga
3
 se o player for para o lado oposto de onde o ataque começou,  o ataque fica parado no ar
Acontece com inimigos grandes quando a tela 
4
Ataque de "música" /Rockbot 2 
As vezes não funciona
E fica no topo da tela

**Comment by protoman** [comment]
OK, seria bom abrir um defeito por problema, então talvez eu divida elas depois. Mas vou colocar minhas observações por hora

1. Esse problema depende do dispositivo e é em uma biblioteca (SDL) de gráficos e som que eu utilizo, então não tem como eu resolver direto no jogo. Teria que abrir um bug com o Pelya, que portou a lib para o Android, e ele não responde os bugs que eu abro para ele, então, vai ser difícil.

2. Não entendi qual o problema?

3. quando a tela o que? Quando a tela se move para a esquerda/direita? O projétil para de se mover mesmo se você voltar para perto dele? Vou tentar reproduzir o problema.

4. Ataque de música? Também não entendi.

**Comment by rikifandubs** [comment]
> 
> 
> 1. Entendo,entendo.
> 
> 2. Não vou saber explicar direito, Então tentarei fazer um vídeo depois
> 
> 3. Esse eu fiz um vídeo :https://youtu.be/bmBJ3WN3TQ8
> 
> 4. Ataque de música? Também não entendi.
Esse eu tirei uma print 
![Screenshot_20210623-174515.png](https://user-images.githubusercontent.com/86270365/123166785-2ba88700-d44c-11eb-826b-d9fc084839d3.png)
Esse ataque em específico, quanto ativado, vai para o tolo da tela e segue rumo a direção que foi disparado, "esquecendo totalmente que o seu objetivo é cair em cima do boss/inimigo"

**Comment by protoman** [comment]
Ah perfeito, obrigado. Vou separar em vários bugs, quando tiver um tempinho e corrigir, provavelmente fim de semana.
MUITO obrigado pelo relatório, ajuda muito.

**Comment by rikifandubs** [comment]
New bug atualização

1
Fases não contém diálogo de Boss (não sei se é bem um bug isso)

2 energy tank deixa player quase invencível

3 alguns stages tem colisão de morte onde não deveriam ter (pelo menos conforme a versão antiga)

**Comment by protoman** [comment]
Por favor, nas próximas vezes abra uma issue aqui para cada problema que você encontrar, porque fica mais fácil para rastrear cada correção. Desta vez, eu vou novamente abrir os bugs e te citar nele (se for necessário, cfe as perguntas abaixo), senão fica uma coisa meio infinita.

1 - não é bug, eu simplesmente não criei esses diálogos.
2 - pode por favor, explicar melhor? Você diz que o jogo fica muito fácil?
3 - consegue tirar uma foto ou explicar o local para eu saber onde é? Não é fácil eu achar no editor olhando cada mapa de cada fase tile por tile :)

**Comment by protoman** [comment]
Fechando a issue por falta de retorno - se houver, eu reabro.
O problema da Lullaby Song foi resolvido em seu próprio bug, etc.
