### ISSUE TITLE
Melhoria e bugs editor

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#123]
1) o editor de "scenes" para de funcionar se modificar muita coisa ao mesmo tempo

2) jet : após pressionar para baixo o player não fica em cima do jet 

Tem mais só que não lembro agora

**Comment by protoman** [comment]
Por favor, informe melhor "para de funcionar se modificar muita coisa ao mesmo tempo", dê um exemplo explicando a sequência de passos para repetir o problema e o que acontece, se fecha o programa, só o editor de scenes ou o programa congela.

Se possível, crie um defeito para cada problema.

**Comment by protoman** [comment]
@rikifandubs  consegue explicar melhor esse defeito?
Finalmente troquei meu PC, e estou vendo os bugs do Rockbot.

**Comment by protoman** [comment]
Corrigi o problema do jet em bug  separado, o problema do editor de scenes ficou faltando detalhes. Se tiver resposta, eu reabro o defeito.

**Comment by rikifandubs** [comment]
Por hora não lembro como fazia o esse bug
