### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#125]
https://youtu.be/mvmuvjS3ddI

Tem "3" bugs no vídeo

Vou escrever aqui.

1) personagem cai do jet quando coloca para baixo.

2) músicas após matar o semi-Boss continua tocando.

3) jogo para de funcionar derrepente (as vezes acontece isso quando abrimos ele)

------------------
Bugs extras.

4) Rockbot não usa uma imagem de fundo, mas uma cor sólida (falado pelo Gmail)

5) jogo não entra na fase quando usa mp3 (versão Pc)

**Comment by protoman** [comment]
Por favor dar mais detalhes sobre o item 5. O jogo fecha, só não toca a música, não carrega a fase? Aparece algum erro na tela de linha de comando:?

**Comment by protoman** [comment]
No futuro, por favor, abrir um item por defeito, senão eu tenho que fazer isso, o que atrasa o trabalho.

**Comment by rikifandubs** [comment]
> Por favor dar mais detalhes sobre o item 5. O jogo fecha, só não toca a música, não carrega a fase? Aparece algum erro na tela de linha de comando:?

Não carrega a fase..
Jogo para de funcionar. (igual no vídeo )
E não aparece nenhum erro na linha de comando.

**Comment by protoman** [comment]
Como eu separei cada problema em um defeito diferente, estou fechando este, pois fica difícil seguir com várias issues em apenas um.
