### ISSUE TITLE
Editor bug

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#126]
Quando trocamos as fases 
O editor não move os inimigos

**Comment by protoman** [comment]
Pode, por favor, dar mais detalhes?
Eu nunca vi problemas com isso, troca de fase, os inimigos aparecem como na
fase selecionada.
--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
O vídeo demonstrar

https://youtu.be/SaWlvLjaMpY

**Comment by protoman** [comment]
Ah, agora entendi; essa troca de posição de estágios eu usava antigamente, quando o jogo ainda era fortemente baseado em megaman, para deixar eles na ordem certa; mas atualmente acho que não é necessário e está sem ser atualizado (por isso não moveu os inimigos, pois mudei um pouco o formato do arquivo que guarda eles).
Se você pretende utilizar esta funcionalidade, de trocar a posição, me avise, caso contrário eu simplesmente irei remover o "swap stages" do editor.

**Comment by rikifandubs** [comment]
> Ah, agora entendi; essa troca de posição de estágios eu usava antigamente, quando o jogo ainda era fortemente baseado em megaman, para deixar eles na ordem certa; mas atualmente acho que não é necessário e está sem ser atualizado (por isso não moveu os inimigos, pois mudei um pouco o formato do arquivo que guarda eles).
> Se você pretende utilizar esta funcionalidade, de trocar a posição, me avise, caso contrário eu simplesmente irei remover o "swap stages" do editor.

Se não for incomodar, poderia manter o "swap stages" ?

**Comment by protoman** [comment]
Claro. Só vai levar um tempinho para eu descobrir porque não está
funcionando, mas sem problema.
--
Iuri Fiedoruk, Software Developer
