### ISSUE TITLE
jogo não entra na fase quando usa mp3 (versão Pc)

### ISSUE THREAD

**Issue by protoman** [protoman/rockbot#131]
Segundo o @rikifandubs o jogo simplesmente sai sem mensagem nenhuma.

**Comment by protoman** [comment]
Pode estar faltando a dll de mp3 no build windows.

**Comment by protoman** [comment]
Testei com o build mais recente e o mp3, colocado na pasta music, e selecionado para a fase via editor, tocou normalmente, tanto no windows como no Linux emulando o Windows (portanto sem nenhuma biblioteca de desenvolvimento no ambiente).

**Comment by rikifandubs** [comment]
Ok, agora me explica uma coisa.
No Android tem uma pasta separada para "mp3"
No editor, não tem a opção de decidir qual vai ser modificado .

**Comment by protoman** [comment]
Certo. Infelizmente isso é uma gambiarra mesmo, por conta de um problema na lib que toca músicas fo format amiga-MOD, e eu fiz a gambi porque muita gente começou a ter isso e nenhum aparelho que eu tenho tem isso, então não tem como eu arrumar, mesmo que possa mexer na lib de MOD, se não consigo ver o problema, não consigo arrumar.

Esta pasta mp3 é usada apenas na versão android mesm, ele procura o mesmo nome de arquivo da pasta músicas, só que troca o final .mod por .mp3 do arquivo. Portanto você precisa ter ambos no android, mesmo que na pasta música já seja um mp3, e ele seja duplicado dentro da pasta musica/mp3.

Seria bom,. de repente, auto-gerar os mp3 no build, mas ia ser um complicador a mais, o certo é corrigir o problema da lib, MAS, o  autor não dá bola.

Pode até ir lá, pedir (em inglês), quem sabe ele lê - https://github.com/pelya/commandergenius/issues/113

**Comment by rikifandubs** [comment]
Assim que possível irei mandar uma mensagem lá. eu não sei muito sobre esse tipo de coisa por conta de eu não ser um programador, então tenho que olhar as palavras que devo escrever .

**Comment by protoman** [comment]
Beleza. Enquanto isso, você pode colocar o mp3 somente na pasta music, e eu
vou verificar que, caso o arquivo não existe em /music/mp3, ele só toque o
original da pasta music mesmo.

--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Vou fazer umas perguntas aqui, assim que possível me manda resposta,please.
1 )O controle de Android tem como ser modificado?
2) Quando vai sair a nova atualização do editor?
3) No seu novo jogo vai precisar de ajuda ? Se sim, posso ajudar ?

**Comment by protoman** [comment]
Para dúvidas, pode me mandar email direto, que aqui é para bugs, por favor.
Vou responder desta vez, mas se quiser algo específico, basta abrir um bug.
1) Nas configurações você pode definir o tamanho e espaçamento dos
controles de tela.  Dá para customizar sim, mas aí tem que fazer um build,
ou habilitar a configuração da SDL para o próprio usuário fazer isso, mas
não é nada amigável.

2) Tem uns bugs sobre ele que eu perguntei o que eram e fiquei sem
resposta, a propósito. Eu fiz um build recente, estou com um PC novo e
configurando o build de Android nesse momento para lançar uma versão nova,
oficial, com as correções e tudo. Prazo? não sei. Com sorte até domingo.

3) O que mais preciso, no momento, é programação, já que muita coisa vai
mudar na engine. Não vai ser open-source como o Rockbot, então vou limitar
a ajuda a eu e minha esposa, pois pretendo cobrar por ele. Agradeço a
oferta :)

--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Sobre o bug do editor de movie

As vezes quando apertava em adicionar ele fechava 
As vezes na ordens dos Scenes 
As vezes aparecia nomes repetidos, ai ele saia (quando apertava, é claro)
Usando a versão Black automática, as letras ficam prestas se tornando impossível de ler 

Achei desnecessário fazer mais de 1 posto pra isso
São coisas tão simples

**Comment by protoman** [comment]
É, mas eu perco o tracking se você fica mandando tudo junto, esqueço e
nunca arrumo :)
--
Iuri Fiedoruk, Software Developer
