### ISSUE TITLE
Editor color letters

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#132]
Deixando o editor na cor Black automática, as letras ficam impossíveis de ler (tudo escuro)

**Comment by protoman** [comment]
Consegue mandar uma screenshot?
Eu testei no linux e no windows (rodando no meu linux) e não tive esse problema do texto continuar preto com o  tema escuro.

**Comment by rikifandubs** [comment]
Eu não sei se a nova versão que vc me passou acontece isso.
Vou ver depois
