### ISSUE TITLE
Editor movie closing

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#133]
Após fazer algumas configurações, o editor multiplica os nomes, apertando no errado ele fecha .

**Comment by protoman** [comment]
"Apertando no errado"?  O que é esse errado?

**Comment by rikifandubs** [comment]
Séria os nomes duplicados

(Tbm não sei se acontece nessa versão)

**Comment by protoman** [comment]
Consegue mandar uma screenshot? Não sei de qual parte você está falando com lista de nomes...
Teve um lugar que realmente duplicava, e eu arrumei, mas era lista de números apenas.

**Comment by rikifandubs** [comment]
Ja foi concertado se eu não me engano.
