### ISSUE TITLE
Relatório de bugs

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#134]
Bugs na nova atualização

https://youtu.be/5_jh4pr2xxU

Todos os bugs são feitos no vídeo

1) Letras praticamente iguais a cor de fundo.

2) Mp3 não carrega o jogo 

------__________------ --------
Acho que esse não pode ser resolvido
3) personagem com tamanho "X" nem sempre funciona o "flog Jump"
Pelo motivo dele ficar (x) blocos para baixo

**Comment by protoman** [comment]
Sobre a cor da fonte, beleza, eu já desconfiava que era ali.

Sobre a música, estranho, porque tanto na minha VM com Windows 7, como
rodando o app via Wine no Linux, rodar com um mp3 funcionou perfeitamente.
Que versão do Windows você tem aí?
Tentou com outros mp3 ou sempre com esse mesmo? (eu testei com esse mesmo,
do Rockbot1 aqui e rodou normal).

Vou tentar fazer um build com debug no console para ver o que pode estar
acontecendo aí, quando tiver um tempo livre - acabaram minhas férias, agora
só feriado e fim de semana ;)
--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
https://youtu.be/G7VnaRpUcRY
--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Já usei muitas músicas, todas fazem as mesmas coisas.
Minha versão do windows, é Win 10

**Comment by protoman** [comment]
Consegue testar com uma música em formato ogg por favor?
--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Sim eu consigo testar, logo logo eu testo, acabei de acordar.

**Comment by protoman** [comment]
![image](https://user-images.githubusercontent.com/1305540/138458151-f5d0e731-9f13-4be2-9fb5-6cf4967ba201.png)
