### ISSUE TITLE
Relatório de bug

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#135]
Me ajuda Iuri ;-;

![Screenshot_20210907-093740.png](https://user-images.githubusercontent.com/86270365/132345948-b77a6c72-4fdd-43e2-9d47-f5a10b584105.png)

**Comment by protoman** [comment]
Ah, tem partes que não são pickup menu... Aff, mudar isso é fácil, mas
achar todos os lugares não é. Dá uma fuçada e tenta mandar as telas de
todos os lugares q achar que precisa arrumar.
Infelizmente hoje é feriado mas está com tempestades aqui, por isso não vou
usar o PC, então não vou ter tempo de procurar.

Em ter, 7 de set de 2021 09:40, rikifandubs ***@***.***>
escreveu:

**Comment by rikifandubs** [comment]
Ok

**Comment by protoman** [comment]
Cara, eu fui fazer essa tela de seleção de personagem.... Bah que tu tá
forçando a amizade já, ahahah. A imagem de fundo claramente tinha uma "safe
area" onde vão os textos, você tem que se adaptar à engine um pouco tb, eu
não vou mais ficar trabalhando nela, Rockbot para mim é passado, quero
trabalhar na minha nova engine logo e deixar ele só só para editar (via
editor mesmo) o Rockbot2 que ainda não completei. Os bugs/melhorias do
editor  eu trabalho exatamente por isso ;)

Mas beleza, vou mudar isso desta vez, só que, mesmo assim, tem um problema:
colocar os dois na tela ao mesmo tempo, vai dar problema quando terminar o
jogo e liberar mais dois personagens. Tem que ser um por vez como é no
Rockbot, senão vai dar ruim :)


--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Entendido, peço desculpas.

**Comment by protoman** [comment]
Infelizmente a engine não é tão flexível quanto o usuário gostaria. Eu Modifiquei esta parte para não usar um fundo de cor sólida, mas o que ele está fazendo é colocando a imagem do personagem na tela toda, inclusive sob o texto. A solução seria não apagar o fundo, mas neste caso, o Rockbot não funcionaria como deve e não pretendo alterar o design dele mais.
Minha recomendação é seguir o design do Rockbot e não utilizar aquela área com imagens que mudam.
