### ISSUE TITLE
Error #41.0

### ISSUE THREAD

**Issue by rikifandubs** [protoman/rockbot#137]
Como fazer

Projectiles

Trajectory type: [15] - target_exact
______
 
Quando ativamos esse opção de arma o jogo dá error #41.0

Basta atirar com esse ataque

**Comment by protoman** [comment]
Esse é um erro genérico de arquivo gráfico faltando.
Parece ser relativo à rotação, que usa o gráfico do projétil para fazer ele
em diferentes ângulos. Verifique a imagem usada para o projétil, se ela
está setada e qual a altura e largura dela.

--
Iuri Fiedoruk, Software Developer

**Comment by protoman** [comment]
Outra coisa, certifique-se que o tamanho do projétil, no editor, seja maior
que zero para largura e altura.
--
Iuri Fiedoruk, Software Developer

**Comment by rikifandubs** [comment]
Estava usando o projétil normal do rockbot, então é maior que 0

**Comment by protoman** [comment]
Tenta não usar esse. Pode ser a razão do problema. Quando der eu dou uma
testada, se quiser me mandar o projeto atualizado, tb fica mais fácil.

Em qua, 27 de out de 2021 14:26, rikifandubs ***@***.***>
escreveu:

**Comment by rikifandubs** [comment]
Acabei de descobrir o motivo.

Caso não tenha inimigo
O jogo da erro 41.0 ao atirar
Pois não tem um inimigo para que a arma funcione
