### ISSUE TITLE
Hit points bars are being drawn under 3rd level of tiles

### ISSUE THREAD

**Issue by protoman** [protoman/rockbot#15]
We need to change the order of drawing in game's main loop method.

**Comment by farleyknight** [comment]
Any idea what stage this is happening in?

**Comment by protoman** [comment]
You can see that on Apge Bot's stage.
I have a plan to solve that, that I already partially implemented that. The
thing is that the function that moves player, enemies and objects should be
logically separated from the function that draws them and the map. No logic
should be placed in the show() methods except for changing sprites, colors
and such. Because it now have some inter-dependencies, when I started
isolating pieces, I had to put hit points bars before 3rd level.

I'm also planning, in the long-term, to change how we draw the map, because
I plan to add animated tiles on it, so we can have nice animations in the
map that, right now, are limited to colorcycling.

## 

Iuri Fiedoruk, Software Developer

**Comment by farleyknight** [comment]
For the time being, I've been learning about the code base by finding bugs, but refactoring could also be helpful. As you mention, you have some some separation of concerns issues in the `show()` method. I might throw in some debugging PR's if you're cool with that. Just don't want to start going crazy with it!

**Comment by farleyknight** [comment]
So yea, if you have specific refactoring work, you can create some issues for those as well. I could take on those on top of bug work I'm doing.

**Comment by protoman** [comment]
I'll review all issues and open new ones, when I find the time.
Meanwhile, let me try to fix this issue Just don't mind if I push some
untested code to the GIT, because I can make some small changes here in my
work, but can't test them until I get home ;)

## 

Iuri Fiedoruk, Software Developer

**Comment by farleyknight** [comment]
Yea, I mean, I'm basically following your advice on what's a priority and what's not. Bug fixing, refactoring, writing new features, removing old features, etc, etc. Whatever you need done first I'll do first.
