### ISSUE TITLE
Rename fields in AI Tab.

### ISSUE THREAD

**Issue by NelsonRosenberg** [protoman/rockbot#26]
It would be better if the options "Shoot Projectile" was "Attack #X" so it's easier to understand.

Also, switch the "Reaction" and "Action" headers so that the player is alaways the one action upon the npcs. Like:
- When the player _ACTION_ the npc _REACTION_

Lastly, GoTo is not very friendly. How about: "Next Action" and "Delay To Next Action".

**Comment by protoman** [comment]
![ai_tab_names](https://user-images.githubusercontent.com/1305540/32332077-b0918b2c-bfcb-11e7-8ef7-21f8bfbee5c5.png)
