### ISSUE TITLE
libretro core

### ISSUE THREAD

**Issue by andres-asm** [protoman/rockbot#30]
Hey

Would you be willing to accept a libretro core upstream if we were to make one?
In case you don't know what it is:

https://www.libretro.com/
http://retroarch.com/

**Comment by protoman** [comment]
Hey. I am familiar with libretro, but I don't get what you meant with core upstream. Can you please further elaborate? Thanks.

**Comment by protoman** [comment]
Closing as I don't think the game would work well with libretro and I got no response.
