### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Sun-God Realm: power-up lands in mid-air. 

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#39]
![screenshot_2017-11-05-15-44-41](https://user-images.githubusercontent.com/33324878/32415882-4078a910-c241-11e7-844c-ee5ce314e511.png)

**Comment by protoman** [comment]
Fixed by https://github.com/protoman/rockbot/commit/32b57f7e086cda480bba9ff017b4f5db6265fb6a
