### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Tricky Castle: Mad Hatter enemy does not take damage when moving, does not stay around Beta to fight, has no walking animation. .

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#40]
![screenshot_2017-11-05-15-59-41](https://user-images.githubusercontent.com/33324878/32416137-a5343dee-c244-11e7-8db7-f2c4a9a40c0e.png)

![20171105_160410](https://user-images.githubusercontent.com/33324878/32416244-a881f21e-c246-11e7-91af-84bcc9b9c762.gif)

**Comment by protoman** [comment]
Fixed by https://github.com/protoman/rockbot/commit/1aa08676ed4eda5c7392a38cd1d24c736685d037
