### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Tricky Castle: bunnies jumping out of hat - drawing/position error on bunny entry.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#41]
![20171105_160332](https://user-images.githubusercontent.com/33324878/32416590-f829280a-c24b-11e7-8d5e-6e165504c09c.gif)

**Comment by protoman** [comment]
WoW, nice catch.

**Comment by ghost** [comment]
In latest update, 1.20.041, they seem to not be mispositioned as previously, they are coming out fine now, but the effect is somewhat strange, because it seems as if they are coming out a bit out of the box - some special effect is needed, smoke or a flash to make them appear to come out of the *middle* of the box.  So, instead of maybe sliding up, they should just appear on top of the box - a puff of smoke first appears on top of the box, to revels the bunny.

**Comment by protoman** [comment]
As this is fixed, I will close the issue. The effect is meant to be not very complex anyway.
