### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Tricky Castle: Mad Hatter enemy goes behind save point computer and does not take damage (did move out of there eventually).

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#43]
![screenshot_2017-11-05-16-00-51](https://user-images.githubusercontent.com/33324878/32416628-833f02d4-c24c-11e7-932b-1458526735aa.png)

**Comment by protoman** [comment]
Hum, I think he was getting damage, but objects should be drawn under, not above, enemies.

**Comment by protoman** [comment]
Fixed by https://github.com/protoman/rockbot/commit/22d2a9ac183d7c525b162291548e527231e85906

**Comment by ghost** [comment]
even his shots go behind he save terminal, and they pass by
