### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Crystal Maze: colorful blocks are badly synchronized when playing after a respawn.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#44]
Beta was killed when he dashed to the left screen side at the beginning of the stage.  He respawned and continued his journey to meet the bad blocks not wanting to position themselves nicely.  

![bad blocks sync](https://user-images.githubusercontent.com/33324878/32439759-684c860a-c2f0-11e7-81d6-b47f2be54808.gif)

**Comment by protoman** [comment]
Oh, looks like I need to call the method that resets objects timers on game::restart_stage() method.
