### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Beta can dash past leftmost screen side at stage start - to his demise..

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#45]
I don't know if this can happen with Rockbot.  In an earlier version of the game, probably the previous one, I did notce that on some stages it was possible to jump off the leftmost side at stage start with Rockbot, notably on the Crystal Maze stage, as I remember.  But Beta can do this on any stage, except the Dark Mine - I thiink, because there is a wall there, but did not try it.

![jump off and die at start of stage](https://user-images.githubusercontent.com/33324878/32439897-1dbd6c2a-c2f1-11e7-8aec-9705a9e06b4b.gif)

**Comment by protoman** [comment]
Ouch, I had this fixed before, but it looks like it returned from ashes.
The collision method was changed to allow player to be pushed out of screen my maps/objects in the auto-scrolling stages, so I need to add a check in character::slide() method itself instead.
