### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] When restarting a completed stage, where the boss was previously defeated and cannot be fought, we are always presented with a dialogue with the boss.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#46]
When restarting a completed stage, where the boss was previously defeated and cannot be fought, we are always presented with a dialogue with the boss - but we cannot fight the boss again.

![false start dialogue](https://user-images.githubusercontent.com/33324878/32440001-907447a2-c2f1-11e7-9894-602f62cbfbfa.png)

**Comment by protoman** [comment]
I was debugging the dialogs and left out the check for stage completion.
But lately I am wondering if it is not better just to let the player fight the boss once again. What do you think?

**Comment by ghost** [comment]
Please read my previous e-mail abut his matter.  I wrote to you about a game design strategy that creates two modes of play: "Story" and "Free Play".  This system of gameplay is notably in LEGO Batman, which I'm currently also playing.  First Story mode has to be completed on specific and predefined terms, with limited resources and possibilities, while the Free Play mode allows us to play however we want, allowing us to use all equipment that we have gathered in the game so far.  Such gameplay design strategy extends gameplay time and gives a variety of gameplay.

Implementing such a strategy here would allow us to replay any stage in one of two ways, every time we play it: 
1) in Story mode, we play the level (again) with predefined goals set by the designer, with limited equipment/ammo and other resources - to "guide" the player on specific terms; only specific parts of the level can be accessed, perhaps even a in specific and predefined order.  The boss is always present in this scenario.

2) In Free Play the player can use all equipment and anything that he/she owns - to play the level, basically, in any way he/she pleases, using any possibilities and resources available to move around the level in any way possible.  A players imagination is the limit in this mode, and the player can experiment with the level, trying to do anything.  The boss here might not be available, especially to underline that the level has been finished and is in a special mode of play.  Instead of the regular boss, a special boss might be present or something else in his absence, to give the player more variety of gameplay.  And in Free Play mode, IMO, there should be much more enemies, "bullet hell", "non-stop attacks", etc.  This mode should be wild, the player has more freedom of navigation and interaction, but will be much more challenged by the environment to get anywhere.  This would definitely give variety of gameplay, extending playtime and giving much more satisfaction out of the game.

Implementing such two modes for all levels would also help in testing the game.  Instead of having to clear app data to have a fresh game start, we can replay any level in Story mode to have the same gameplay design every time, or in the Free Play mode we have much more action and freedom, to see better how the game performs.

The game has much potential, it all depends on how you design it.  Just because the levels are small and their layout is simple, does not mean that the game has to be simple, short and casual.  Within these levels, a player can go through "hell" and remember it for long.  Traps, one-way corridors and doors, which will create a maze, along with a bombardment of enemies - will give a player much to do.  Hidden items will help even more..

**Comment by protoman** [comment]
I has read the idea. I just don't want to add it right now.
There is a high number of issues I need to address, caused by the added new features, so it is now time to stabilize the code, I don't plan to add major features until I make the open-beta release for the full version.
That said, it is a neat concept for version 2.0.1 ;)

**Comment by ghost** [comment]
I cannot blame you..  Having ideas is one thing, designing and implementing them is another..

These are just ideas for the future, if you want them.  I'm just brainstorming.

The game is great already, though.  It is well made overall, but you have to take into consideration that compared to the general offer of games available, it is very casual.  Maybe you want it that way - fine.  Casual games are needed as well, I play them sometimes as well.  And in fact, this is what got me interested in this game, it's a neat little story, easy and relaxing, just fun!

Game development is a difficult craft.  You got the graphics - very nice, you have a nice design overall, and the game is very playable already.  Since you're so good at this, and you seem to be able to do much more - and you want to do more; well, I'm just saying..  You know best what you want and what can be _really_ done, within reasonable limits.

It's your fault, that you are a good game developer.  Players on the other hand always want more ;)

**Comment by ghost** [comment]
Making the bosses permanent is going to break the Story mode of your game.  It's also going to make the game look cheap and unfinished.  This game is based on Story mode.  If it was pure arcade, than having the bosses at all times might me fine, but then again not always.  This game depends - IMO - on the fact, that we have a nice intro when we get to a stage for the first time - it's a nice Story mode, and once we finish the level; ie we defeat the boss - the level is clear (mostly, minor enemies are respawning).  So we should not see that intro story once we clear a level.  In fact, some other enemies might not be present as well, to make it clear that the level is clear.

Also, have a "level clear" status on the level can be a nice thing when we return to it to find secrets and get to places that we could not previously.  Maybe even you can make a status, where some places *cannot* be accessed until the boss is cleared.. also some items cannot be taken until the boss is defeated - and we have to return to the level again, to get the stuff.  This would be really fun and greatly increase gameplay value!
