### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Crystal Maze: enemies not respawning at certain point.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#47]
When Beta goes to the right - where there is a dead-end room, and the he goes back to the left, gets back to this part with the ladder - the enemies here do not respawn, but when we go up the ladder and down agian, the enemies do respawn.

![enemy not respawning](https://user-images.githubusercontent.com/33324878/32440117-0ac8cca8-c2f2-11e7-8080-86319ac3d3fb.png)

**Comment by protoman** [comment]
This is how the engine works, when you go up/down in the ladder, another map is loaded, thus all itens and enemies are reset. But when I use an horizontal scrolling lock, like this one, it is just to prevent scrolling where I do not want it.
So I am closing the issue.
