### ISSUE TITLE
[ Rockbot 1 | 2.00.093 | Android | Play Store ] Infoway: power-up lands in mid-air.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#50]
![landed in mid-air](https://user-images.githubusercontent.com/33324878/32443405-387a6b86-c2ff-11e7-8e69-5beb344672f4.png)

**Comment by protoman** [comment]
This was fixed already in https://github.com/protoman/rockbot/commit/32b57f7e086cda480bba9ff017b4f5db6265fb6a

Please update your version, I've just released 1.20.041 for Rockbot1.
