### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Infoway: fading blocks can get us stuck.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#53]
when jumping on the red block,
when it is not there, and when
Beta is at block position as the
block appears, he will get stuck
there, standing in front of the block,
a bit below it and not be able to move
(he has somewhat moving animation,
jumping animation too) but he has to
wait for the block to disappear so that
he can move 

![stuck on block](https://user-images.githubusercontent.com/33324878/32477209-c1ca6bfc-c37c-11e7-852c-89ae68baaafe.png)

**Comment by protoman** [comment]
Fixed in c8635e55ad66f57e661268c2fba36754c6758923
