### ISSUE TITLE
Rockbot 1 | 1.20.041 | Android | Play Store ] Infoway: pop-up enemies on stairs are displaced

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#54]
Issue #52 has not been fixed (sorry about wrong app version number).

**Comment by protoman** [comment]
I thin you can edit the issue to reopen it, if not fixed; instead of opening a new one.
Anyway, I fixed this problem in a different way this time, reducing metool's width for the stand frame, so they now again fall into position correctly.

**Comment by ghost** [comment]
I can add to existing issues, but won't it be too much if I specify problems from the whole game in one place?  You asked to break up issues, to make them as precise as possible.
