### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Crystal Maze: BlueShield enemy takes frontal damage.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#57]
Issue #48 has not been fixed (gave bad app version number).

**Comment by ghost** [comment]
I noticed, that the BlueShielder does repel gunfire just after turning around and facing our hero, then he is vulnerable again form the front - I noticed it in the final boss stages.

**Comment by protoman** [comment]
I can't reproduce the issue right now. Can you please give me more details like stage, character used or a video of the problem?

**Comment by ghost** [comment]
You should provide cheat mode, cheat codes (with button sequences or a password menu) so that we can skip to any stage.

Especially since the game is still in pre-release development, there should be a menu to quickly jump to *any* game area..

And yeah, when you shoot constantly at a Shielder, when he turns and is already facing the hero, he will take damage, that's what I got there, as stated, for the blue type.  It seems like the repulsion effect should turn on earlier after that enemy turns around, that's what it looked like.

**Comment by protoman** [comment]
Cheat was implemented.
I think the front-shield is already fixed also.
