### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Beta can dash past leftmost screen side at stage start - to his demise..

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#58]
Issue #45 has not been fixed (gave wrong app version).

**Comment by protoman** [comment]
Sorry, I don't understand. You mean you can still reproduce the issue with the version that states the issue or fixed, or the fix didn't get into that last version?

**Comment by ghost** [comment]
No, that was still for version 1.20.041.  The update version, 1.20.042 has it fixed.  If it was in the new version, I would make a new issues with an explicit version number, or state that in a comment for an existing old issue.  So again, it's fixed now.
