### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Coil Frog does not work on save point.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#60]
First noticed in Infoway, but also happens in intro stage, so assuming it's game-wide.

![coil frog not working on save spot](https://user-images.githubusercontent.com/33324878/32489326-e2a84a6e-c3af-11e7-8702-e637ec6ae7da.gif)

**Comment by protoman** [comment]
Verified and took note. 
I need to implement a kind of priority for execution of objects that collide with the player, otherwise it will ignore second one onwards.
