### ISSUE TITLE
Improve icon for Dynamite-got weapon

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#61]
TimeBomb invokes TimeFreeze and vice-versa.

(I'll report the other stuff on this video in seperate issues.)

![messed up weapons shielder getting stuck lader problem](https://user-images.githubusercontent.com/33324878/32489475-6c64a90a-c3b0-11e7-9a9b-66fa8333313b.gif)

**Comment by protoman** [comment]
That is actually correct. I need a better icon for the Dynamite time-stopper, but it is not inverted.
