### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Tricky Castle: secret ladder does not support Beta.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#63]
It's like a hole there, but the ladder can be used.

![messed up weapons shielder getting stuck lader problem](https://user-images.githubusercontent.com/33324878/32489788-5ed0339e-c3b1-11e7-8a5e-c140bf9dd604.gif)

**Comment by ghost** [comment]
and while Beta is on the ladder, he is always above the bricks:

![above ceiling wall](https://user-images.githubusercontent.com/33324878/32690300-d98d2a1a-c6f4-11e7-9864-5cb366e4af7e.png)

**Comment by protoman** [comment]
That is made by design, actually. It is meant to be confusing, after all, it is tricky castle's secret ;)
