### ISSUE TITLE
[GENERAL] Player gets stuck on disappearing blocks

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#65]
The block disappeared and Beta jumped to land on it, when it was to appear.  But he jumped too soon, and when the block did appear, Beta was practically on the same position, a bit lower - and he was stuck there until the block disappeared.  While stuck, he could make tiny little jumps and tiny movement animation.  This might be in the whole game.

![stuck on block](https://user-images.githubusercontent.com/33324878/32490062-39607b4a-c3b2-11e7-94d6-e3fcae66df4d.png)

**Comment by protoman** [comment]
I need to check how Megaman handles this, if block only is solid when player is above it or if it kills the player.

**Comment by protoman** [comment]
Fixed in c8635e55ad66f57e661268c2fba36754c6758923
