### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Intro Stage: red orb bots are running away.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#66]
What did you do to them?  They're all scared now and they run away from Beta!  The just go at him directly the first time, and when he jumps over them or just quickly outruns them, they continue to go left and they go up into the sky.. (I think they first hit the ground at an angle and then they bounce off and go on left and up into the top, to disappear).  They don't follow Beta anymore!

I said, do them more aggressive - not shy and cowardly!  What did you say to them?? 😱

**Comment by protoman** [comment]
Fixed in https://github.com/protoman/rockbot/commit/585fd08de3a63d1a060fad8df40864036f1c748d
