### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] We cannot leave the final boss level at any time, like the "normal" levels.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#67]
When playing the first stages with the bosses, we can leave the current stage to go back to the stage selection menu.  But when we play the final Dr. D boss stage, we can't.   But as we progress through parts of the final boss part, we are on the stage selection screen - in between these parts (as I remember from last update).

**Comment by protoman** [comment]
Did you had finished the game before? You know, the leave stage should only be possible if you already finished the given stage.

**Comment by protoman** [comment]
You can now leave stage even if not finished by pressing X (dash/slide) button.
