### ISSUE TITLE
[ Rockbot 1 | 1.20.041 | Android | Play Store ] Final boss stages/first part: Tiime-Freeze weapon is not working on death rays - cannot continue gameplay.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#69]
This weapon - though I suggest we call it a tool (please make this official?), so: the time-freeze tool is not stopping the death rays, and notice that when I press quickly my fire button, Beta also fires his basic weapon in between the time-freezing tool invocation.  And I think - I noticed sometimes - that the time-freeze tool cannot be used again, once it was used; so I cannot quickly "fire" time-freeze, one "shot" after another - this is certainly a big problem, this has to be fixed so that we can quickly tap to get the time-freeze effect *immediately* after the previous duration just ended, so that we get a *constant* effect.

This problem prevents further gameplay until fixed.

![time-freeze tool not working on death rays](https://user-images.githubusercontent.com/33324878/32494056-713aae4c-c3c0-11e7-9be9-643fa4b13709.gif)

**Comment by protoman** [comment]
Yeah, this weapon is not meant to stop objects, only enemies.
I can add support to stop objects, but I don't know if that will make the game too cheap :)
