### ISSUE TITLE
Improve "got-weapon" celebration

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#70]
![20171110_155507](https://user-images.githubusercontent.com/33324878/32676436-e905a5fc-c65a-11e7-8ac9-bd10bd17c3f6.gif)

**Comment by ghost** [comment]
I think that after the boss explodes, the upcoming victory animation should come more quickly.  And the hand gestures should be during the flashing, so it's not synced as well?

**Comment by protoman** [comment]
Still showing 3rd level tiles above colored-scene.
