### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Sun-God Realm: turret/cannon is placed too high, horizontal shots are never a threat.  

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#71]
![screenshot_2017-11-10-21-17-46](https://user-images.githubusercontent.com/33324878/32677391-83e2f900-c65e-11e7-82f7-cc50f4f6901f.png)

**Comment by protoman** [comment]
Fixed in https://github.com/protoman/rockbot/commit/3affdc8feb06027c32d61f0e7d48fcc5f38d1888
