### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Some pop-up turrets do not turn around.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#72]
Perhaps this might be intended, but from a gameplay perspective, the pop-up ground turrets should turn around in the direction of our hero and fire that way.

![screenshot_2017-11-10-21-21-33](https://user-images.githubusercontent.com/33324878/32677563-3abbdafc-c65f-11e7-96e5-796acfc82f98.png)

**Comment by ghost** [comment]
the green-helmet turrets in Infoway do turn around, they are the best.

**Comment by ghost** [comment]
same in here: Castle stage part 2:

![screenshot_2017-11-11-15-32-49](https://user-images.githubusercontent.com/33324878/32690451-4a65df64-c6f7-11e7-8972-91dee0907d54.png)

**Comment by protoman** [comment]
Fixed in commit https://github.com/protoman/rockbot/commit/ca3e9745f775a3561dbe8f925777f461cd4b2dff
