### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] head standing.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#78]
was using the Coil Frog, there was a Coil Frog there - quickly changed to Jet and could not use Jet for a moment, had to wait for Frog to disappear, then used Jet to fly to the one-up head and could stand on it for a few moments, before Beta "got" the head and was on ground (the one-up head disappeared)

![screenshot_2017-11-10-22-31-39](https://user-images.githubusercontent.com/33324878/32680342-7a3b4e50-c66a-11e7-9c30-628220687848.png)

**Comment by ghost** [comment]
it's not the power-up "head", here I show how I stand on air, above the power-up:

![jet error](https://user-images.githubusercontent.com/33324878/32690275-981e5d88-c6f4-11e7-840f-01d714c86cf8.png)

**Comment by protoman** [comment]
Removed 1up from that stage. We do not have life/1up anymore, but a few items were left on the stages.
