### ISSUE TITLE
Save point active status is reset when changing maps

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#81]
activated save point, went back and upon return seems that the save point is not set?  so which save point is set then?  or is this just an animation thing?

![20171111_132104](https://user-images.githubusercontent.com/33324878/32689841-f875206c-c6eb-11e7-9bd3-27369390dbf0.gif)

**Comment by ghost** [comment]
On Daisie stage the same, so assuming this is in the whole game.

**Comment by protoman** [comment]
Hum, I never cared about making the checkpoint active forever. This can be done, of course, but it itsn't a major problem, IMHO. Alas, only one should be active in this case.

**Comment by protoman** [comment]
Closing as Nont An Issue.
