### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Castle Stage, part 1: app crashes just after defeating Disc Boss.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#82]
Yep, it crashed just like that.  Previously, these games *never* crashed for me.  So the previous crashes reported were also caused by the app (on intro stage), not by external sources, like I thought.

**Comment by ghost** [comment]
crashed again after defeating Castle Stage part 2 boss - showed the stage selection menu for a second and crashed..

**Comment by protoman** [comment]
Please, provide logcat for the crash so I can get more details.

**Comment by protoman** [comment]
Can't reproduce, tthus closing issue.
