### ISSUE TITLE
[ Rockbot 1 | 1.20.042 | Android | Play Store ] Castle Stage, part 3: serious error: fading blocks get hero stuck.

### ISSUE THREAD

**Issue by ghost** [protoman/rockbot#87]
this is not that serious a bit before the boss, where there is ground to fall on and we can wait for the block to fade, to let us free.

but when in this boss room, when we do get stuck with such a block - easy to happen, there is no way to get loose..

![screenshot_2017-11-11-15-53-44](https://user-images.githubusercontent.com/33324878/32690585-594171b8-c6f9-11e7-8756-07695eead8c4.png)
![screenshot_2017-11-11-15-55-35](https://user-images.githubusercontent.com/33324878/32690586-5973bd44-c6f9-11e7-9bd1-a6d85d9b189d.png)

**Comment by protoman** [comment]
I checked the bahavior in megaman, it just moves player to above the block, so I'm doing that.
