### ISSUE TITLE
Enemies getting stuck

### ISSUE THREAD

**Issue by protoman** [protoman/rockbot#9]
*****\* Daniel Durda:
Few more issues encountered.
I was playing through and I encountered some pretty big bugs.

2 of them in ape bots stage. And one in mummy bots stage. I got to the boss and died. The next life started in the hallway and I immediately fell through the floor.
This also happened in mummy mans stage which I managed to take a picture of. _picture in the desert_

The other issue was also in ape mans stage. He jumped at me and got stuck in the first pixel inside the wall and ape man fell through the floor and his health disappeared but the level didn't end. I was just stuck in game until I restarted the app. I did take a picture of this as well. _picture in the jungle_

**Comment by farleyknight** [comment]
This is consistently happening (for me) on the Mage Bot stage. There's a shield guy that keeps getting stuck  under the blue box. I'll look at that and try to figure out an engine change that would prevent enemies from getting stuck in general, but it may be a level change as well. Not sure.

**Comment by protoman** [comment]
Oh, I know what the problem is. We need to add collision check between
objects and enemies, much like we do for player-objects. But in the case
npc-object, we should not activate them.
I can work on this problem. I had ssen that but forgot to add it to my
"todo" list.

## 

Iuri Fiedoruk, Software Developer
